# Thesis-conformance check against Fastl & Zwicker (2007) experimental
# fluctuation-strength curves, transcribed from Osses, García & Kohlrausch
# (2018 PhD thesis), Table B.1 (AM tones / AM broadband noise / FM tones,
# fmod in {1,2,4,8,16,32} Hz), plus the reference implementation's own
# output on every one of those 18 stimuli.
#
# Two assertions per grid point:
#
# 1. ORACLE PARITY (all 18 points): `fluctuation_strength_osses` on the
#    stimulus must reproduce SQAT's `FluctuationStrength_Osses2016`
#    (CC BY-NC, github.com/ggrecow/SQAT @ 00b449e40599f1c1ef4abe0596094552213d57eb,
#    Octave 11.3.0 / octave-signal 1.4.7) on the IDENTICAL samples, both
#    per frame and as the mean. The oracle values are vendored in
#    test/data/sqat_fs_crosscheck.jl (`thesis_*` cases, generated by
#    scripts/generate_sqat_fs_crosscheck.jl). Measured 2026-09-02: max
#    relative deviation 4.3e-10 on the mean and 3.8e-9 per frame across all
#    18 points; rtol 1e-6 leaves > 2.5 orders of margin and matches
#    test_crosscheck_sqat_fs.jl. Any failure here is a transcription bug.
#
# 2. PUBLISHED-CURVE GATE (only where the reference model meets it):
#    `abs(computed - ref)/ref <= 0.30`, i.e. 30 % OF THE REFERENCE value
#    (deliberately not `isapprox(; rtol)`, which scales by max(|a|,|b|) and
#    would grant overestimating points an effective ~43 % bound). This gate
#    is asserted for the seven points where the reference model itself
#    reproduces the published curve on these stimuli (AM fmod 1/4/8/16 Hz,
#    FM fmod 1/2/4 Hz). Elsewhere the reference model does not, so a
#    published-curve gate would assert a property the model does not have;
#    those points are covered by assertion 1 and documented below. An
#    informational 30 %-of-reference tally over all 18 points is emitted
#    regardless.
#
# --- Where the reference model misses the published curve (measured) ---
#
#   point        ours = SQAT  published  ratio   SQAT's own validation figure
#   AM  2 Hz      1.1096       0.84      1.32x   ~1.13 on the Zenodo wav: same miss
#   AM 32 Hz      0.0161       0.06      0.27x   ~0.01: same miss
#   FM  8 Hz      2.5990       0.70      3.71x   ~2.45: same miss (thesis §B.4.1:
#   FM 16 Hz      1.2125       0.27      4.49x   ~1.05  model overestimates FM for
#   FM 32 Hz      0.0546       0.02      2.73x   ~0.02  fmod > 4 Hz, peak shifted to 8 Hz)
#
# "SQAT's own validation figure" = validation/FluctuationStrength_Osses2016/
# {1_AM_tones_fmod,3_FM_tones_fmod}/figs/*.png in the pinned checkout, which
# plot SQAT's results on its Zenodo validation dataset
# (doi:10.5281/zenodo.7933206) against the same published values. Our
# synthetic AM tones reproduce those dataset results closely; our FM tones
# reproduce the qualitative misses but not the exact values (e.g. FM 1 Hz:
# ours 0.844, SQAT-on-dataset ~0.58 read off the figure), so the FM synthesis
# convention in fs_stimuli.jl (cosine carrier, sinusoidal phase term) is
# inferred, not verified against the dataset. This is why FM 1/2/4 are gated
# on the published curve only as a bound, with oracle parity as the real
# fidelity claim.
#
# --- AM broadband noise: not gated on the published curve ---
#
# SQAT's stimulus for this row (file names `randomnoise-Fc-8010_BW-15980_
# Fmod-*_Mdept-100_SPL-60`) is a 20 Hz-16 kHz band, the SAME band as
# `fs_am_noise(16000, ...)`; an earlier note here blaming a bandwidth
# mismatch was wrong. Yet SQAT's own validation figure shows the reference
# model within the 10 % JND of the published curve at fmod 2/4/8 Hz on its
# dataset noise, while on our noise the same model (oracle parity to 1e-9,
# assertion 1) gives ~2x the published values at 2/4/8 Hz. Measured
# sensitivity of our stimulus at fmod = 4 Hz, 60 dB: m = 0.3/0.5/0.7/1.0
# gives 0.42/1.15/2.17/3.88 vacil; Gaussian vs uniform noise, brick-wall
# vs unfiltered, 4 s vs 8 s, and white vs pink shaping all change the
# result by < 10 %. So the dataset's modulation-depth or level convention
# for noise differs from a plain m = 1 post-modulation-RMS-calibrated
# signal, in a way the file name does not reveal. The dataset itself could
# not be fetched to settle it (Zenodo returned 403 "unusual traffic" on
# 2026-09-02). Until it is, this row asserts oracle parity only; a
# published-curve pass or fail on our stimulus would be meaningless either
# way (fmod = 1 Hz happens to land within 30 %).
#
# Suite totals: this file contributes 0 to the Broken column.

isdefined(@__MODULE__, :fs_am_tone) ||
    include(joinpath(@__DIR__, "support", "fs_stimuli.jl"))
isdefined(@__MODULE__, :SQAT_FS_CASES) ||
    include(joinpath(@__DIR__, "data", "sqat_fs_crosscheck.jl"))

# (fmod [Hz], FS [vacil]) — experimental references, Osses 2018 thesis Table
# B.1 (transcribed from Fastl & Zwicker 2007 via the thesis).
const FS_REF_AM_70DB = [(1.0, 0.39), (2.0, 0.84), (4.0, 1.25), (8.0, 1.30), (16.0, 0.36), (32.0, 0.06)]
const FS_REF_FM_70DB = [(1.0, 0.85), (2.0, 1.17), (4.0, 2.00), (8.0, 0.70), (16.0, 0.27), (32.0, 0.02)]
const FS_REF_AMBBN_60DB = [(1.0, 1.12), (2.0, 1.58), (4.0, 1.80), (8.0, 1.57), (16.0, 0.48), (32.0, 0.14)]

# Points where the reference model reproduces the published curve on these
# stimuli (header); the 30 %-of-reference gate is asserted only for these.
const _FS_PUBLISHED_GATED = Set([
    ("am", 1.0), ("am", 4.0), ("am", 8.0), ("am", 16.0),
    ("fm", 1.0), ("fm", 2.0), ("fm", 4.0),
])

const _FS_ORACLE_RTOL = 1e-6   # measured max 3.8e-9 per frame, 4.3e-10 on the mean

# Gate (roughness/D&W convention): within 30% OF THE REFERENCE value.
const _GATE_RTOL = 0.30
_fs_gate(computed, ref) = abs(computed - ref) / ref <= _GATE_RTOL

_fs_oracle_case(kind, fmod) =
    only(filter(c -> c.name == "thesis_$(kind)_$(Int(fmod))hz", SQAT_FS_CASES))

@testset "thesis Table B.1 conformance (Fastl & Zwicker via Osses 2018)" begin
    within30 = 0
    total = 0

    for (label, kind, refs, synth) in (
            ("AM tones, 70 dB SPL", "am", FS_REF_AM_70DB,
                fmod -> fs_am_tone(1000.0, fmod, 70.0, 4.0, 44100.0)),
            ("FM tones, 70 dB SPL, fdev=700 Hz", "fm", FS_REF_FM_70DB,
                fmod -> fs_fm_tone(1500.0, fmod, 700.0, 70.0, 4.0, 44100.0)),
            ("AM broadband noise, 60 dB SPL", "bbn", FS_REF_AMBBN_60DB,
                fmod -> fs_am_noise(16000.0, fmod, 60.0, 4.0, 44100.0)),
        )
        @testset "$label" begin
            for (fmod, fs_ref) in refs
                sig = synth(fmod)
                oracle = _fs_oracle_case(kind, fmod)
                @assert sig == synthesize_case(oracle.name)[1]  # same samples the oracle saw
                r = fluctuation_strength_osses(sig, 44100)
                total += 1
                within30 += _fs_gate(r.fluctuation_strength, fs_ref)
                @testset "fmod=$(fmod)Hz" begin
                    # 1. oracle parity on identical samples
                    @test length(r.fluctuation_strength_over_time) == length(oracle.fluct)
                    @test isapprox(r.fluctuation_strength_over_time, oracle.fluct; rtol = _FS_ORACLE_RTOL)
                    @test isapprox(r.fluctuation_strength, oracle.fs_mean; rtol = _FS_ORACLE_RTOL)
                    # 2. published curve, where the reference model meets it
                    if (kind, fmod) in _FS_PUBLISHED_GATED
                        @test _fs_gate(r.fluctuation_strength, fs_ref)
                    end
                end
            end
        end
    end

    @info "thesis Table B.1: $within30/$total points within 30% of the Fastl & Zwicker reference curves (informational)"
end
