# Transcription cross-check: SQAT's FluctuationStrength_Osses2016 (CC BY-NC,
# github.com/ggrecow/SQAT @ 00b449e40599f1c1ef4abe0596094552213d57eb) run
# under Octave 11.3.0 (octave-signal 1.4.7) — oracle only, no code
# transcribed (see .superpowers/sdd/fs-oracle-pins.md). Fixtures are
# generated by scripts/generate_sqat_fs_crosscheck.jl from signals produced
# by this package's own `synthesize_case` (test/support/fs_stimuli.jl), so
# both sides of every comparison below see IDENTICAL input samples; any
# disagreement is either a transcription bug in `fluctuation_strength_osses`
# or the expected float-reduction-order "dust" mechanism documented below —
# never a difference in stimulus.
#
# Tolerance procedure (same as test_crosscheck_mosqito_roughness.jl): start
# rtol = 1e-6 on `fluctuation_strength` (fs_mean) and per-frame
# `fluctuation_strength_over_time`; if a case fails but its measured max
# relative deviation is < 1e-3, set rtol to 10x the measured value and
# record it here; >= 1e-3 requires a per-channel probe (dump h0, maxabs of
# the bandpass envelope, zero-variance/exact-zero flags, and ki per channel
# for the worst frame on both sides — see scripts/probe_fft_dust.jl for the
# roughness-side template) and controller adjudication before ANY loosening.
# Deterministic quantities (h0, mdepth) must match to ~1e-12 in such a probe;
# only covariance-of-dust channels (a channel whose bandpass envelope is
# analytically zero but numerically pure round-off, so the exact-zero guard
# in the cross-covariance stage passes rounding noise on both sides, exactly
# like roughness's all-nonzero guard) may be excused.
#
# Measured max relative deviations, under `--check-bounds=yes` (Pkg.test's
# default, which changes float-reduction/SIMD order relative to an
# interactive `julia --project=.` REPL run — Task 4 measured a ~1e-6-class
# effect on one specific-FS channel via this exact mechanism, see
# fs-task-4-report.md's "fix wave" section; the same
# `_fs_cross_covariance`/`_fs_specific` pipeline is exercised here). Measured
# 2026-07-08, this machine:
#
#   case                max rel dev (fluct)     max rel dev (fs_mean)   rtol used
#   anchor_44k          2.30e-9                 2.34e-10                1e-6
#   anchor_48k          2.12e-9                 5.26e-11                1e-6
#   am_8hz_70db         1.75e-10                2.68e-11                1e-6
#   fm_tone_4hz         7.38e-13                1.20e-14                1e-6
#   am_bbn_4hz          2.60e-12                1.36e-13                1e-6
#   stationary_anchor   8.44e-10                3.64e-10                1e-6
#   short_fallback      8.10e-11                7.67e-11                1e-6
#
# All 7 cases hold the brief's default rtol=1e-6 with >2.5 orders of
# headroom (worst case 2.3e-9 on anchor_44k, ~435x; five of seven cases
# exceed 3 orders) — no tolerance loosening or per-channel
# dust probe was needed; the >1e-3/1e-2 escalation paths in the procedure
# above were not exercised.
#
# (`tone_25bark` is exact 0.0 on both sides — already asserted directly in
# test_fluctuation_strength.jl's "24 Bark behavior" testset, not repeated
# here as a loop case, per the brief's note that re-testing it is optional.)

isdefined(@__MODULE__, :fs_am_tone) ||
    include(joinpath(@__DIR__, "support", "fs_stimuli.jl"))

@testset "cross-check vs SQAT FluctuationStrength_Osses2016" begin
    # Guarded: test_fluctuation_strength.jl already includes this fixture.
    # Re-including would REDEFINE const SQAT_FS_CASES — documented UB on
    # Julia ≤ 1.11 ("may fail, cause incorrect answers, or produce other
    # errors"), and the empirical trigger of a GC abort (SIGABRT in
    # gc_mark_outrefs) on 1.10.11 once enough GC cycles separate the
    # redefinition from its use. Julia 1.12's binding partitioning makes
    # rebinding well-defined, which is why the crash was 1.10-only.
    isdefined(@__MODULE__, :SQAT_FS_CASES) ||
        include(joinpath(@__DIR__, "data", "sqat_fs_crosscheck.jl"))
    rtols = Dict(                     # measured under Pkg.test, see header table
        "anchor_44k" => 1e-6, "anchor_48k" => 1e-6, "am_8hz_70db" => 1e-6,
        "fm_tone_4hz" => 1e-6, "am_bbn_4hz" => 1e-6,
        "stationary_anchor" => 1e-6, "short_fallback" => 1e-6)
    for c in SQAT_FS_CASES
        haskey(rtols, c.name) || continue
        sig, fs, method = synthesize_case(c.name)  # same params as the fixture generator
        @assert fs == c.fs && method == c.method
        r = c.method == 0 ?
            fluctuation_strength_osses(sig, c.fs; method = :stationary) :
            fluctuation_strength_osses(sig, c.fs)
        @testset "$(c.name)" begin
            @test length(r.fluctuation_strength_over_time) == length(c.fluct)
            @test isapprox(r.fluctuation_strength_over_time, c.fluct; rtol = rtols[c.name])
            @test isapprox(r.fluctuation_strength, c.fs_mean; rtol = rtols[c.name])
            @test isapprox(r.time_axis, c.t; atol = 1e-12)
        end
    end
end
