# AUTOGENERATED by scripts/generate_mosqito_crosscheck.jl — do not edit.
# (case name, weighting, expected sharpness [acum]) computed by MoSQITo
# sharpness_din_from_loudness (Apache-2.0) from this package's own
# specific loudness, with N = 0.1*sum(N') passed explicitly.
const MOSQITO_CROSSCHECK = [
    ("readme_example", :din, 0.8875606824149247),
    ("readme_example", :aures, 1.5294636830592012),
    ("readme_example", :bismarck, 0.8808954771090867),
    ("readme_example", :fastl, 0.8573658124656721),
    ("rising_ramp", :din, 3.0465503530672904),
    ("rising_ramp", :aures, 6.019002273802992),
    ("rising_ramp", :bismarck, 2.8195587384209766),
    ("rising_ramp", :fastl, 2.7187572867078895),
    ("falling_ramp", :din, 1.0895946225148319),
    ("falling_ramp", :aures, 1.6764168387684004),
    ("falling_ramp", :bismarck, 1.0692038502390562),
    ("falling_ramp", :fastl, 1.0368846201309436),
]
