"""Called by generate_mosqito_roughness_crosscheck.jl — not directly.
Reads {name, fs, overlap, signal} cases from JSON (argv[1]), runs MoSQITo's
roughness_dw, writes a Julia data file (argv[2]) with per-frame R."""
import json
import sys

import numpy as np
from mosqito.sq_metrics import roughness_dw

cases = json.load(open(sys.argv[1]))
lines = [
    "# AUTOGENERATED by scripts/generate_mosqito_roughness_crosscheck.jl — do not edit.",
    "# (case, fs_analyze, overlap, MoSQITo per-frame roughness [asper]) computed by",
    "# MoSQITo roughness_dw (Apache-2.0) on signals synthesized by this package's",
    "# own test generator — any disagreement is a transcription bug.",
    "const MOSQITO_ROUGHNESS_CROSSCHECK = [",
]
for c in cases:
    sig = np.array(c["signal"])
    R, _, _, _ = roughness_dw(sig, fs=c["fs"], overlap=c["overlap"])
    R = np.atleast_1d(R)
    vals = ", ".join(repr(float(v)) for v in R)
    lines.append(f'    ("{c["name"]}", {float(c["fs"])!r}, {float(c["overlap"])!r}, [{vals}]),')
lines.append("]")
open(sys.argv[2], "w").write("\n".join(lines) + "\n")
print(f"wrote {sys.argv[2]}: {len(cases)} cases")
