"""Called by generate_mosqito_crosscheck.jl — not directly.

Reads specific-loudness cases (JSON, argv[1]), evaluates MoSQITo's
sharpness_din_from_loudness for all four weightings with N = 0.1*sum(N'),
and writes a Julia data file (argv[2]).
"""
import json
import sys

import numpy as np
from mosqito.sq_metrics.sharpness.sharpness_din.sharpness_din_from_loudness import (
    sharpness_din_from_loudness,
)

cases = json.load(open(sys.argv[1]))
lines = [
    "# AUTOGENERATED by scripts/generate_mosqito_crosscheck.jl — do not edit.",
    "# (case name, weighting, expected sharpness [acum]) computed by MoSQITo",
    "# sharpness_din_from_loudness (Apache-2.0) from this package's own",
    "# specific loudness, with N = 0.1*sum(N') passed explicitly.",
    "const MOSQITO_CROSSCHECK = [",
]
for c in cases:
    ns = np.array(c["specific_loudness"])
    n = 0.1 * ns.sum()
    for w in ("din", "aures", "bismarck", "fastl"):
        s = float(sharpness_din_from_loudness(n, ns, weighting=w))
        lines.append(f'    ("{c["name"]}", :{w}, {s!r}),')
lines.append("]")
open(sys.argv[2], "w").write("\n".join(lines) + "\n")
print(f"wrote {sys.argv[2]}")
