# One-time generator for test/data/din45692_band_levels.jl.
#
# Downloads the DIN 45692:2009 chapter-6 reference test signals as vendored
# by MoSQITo (Apache-2.0, https://github.com/Eomys/MoSQITo) and reduces each
# to a 28-band one-third-octave SPL vector via ZwickerLoudnessAudio.
#
# Calibration follows MoSQITo mosqito/utils/load.py: int16 sample / (2^15 - 1)
# is the signal in pascals (1 Pa/FS), first channel only. The signals'
# overall levels are ~65-69 dB (narrowband) / ~50 dB (broadband) — they are
# NOT 60 dB; do not "fix" this.
#
# Reference sharpness values are transcribed from MoSQITo
# validations/sq_metrics/sharpness_din/validation_sharpness_din.py, which
# cites DIN 45692_2009E chapter 6.
#
# Usage: julia scripts/generate_din_reference.jl   (needs network access)

using Pkg
Pkg.activate(; temp=true)
Pkg.add([
    Pkg.PackageSpec(name="ZwickerLoudnessAudio", version="0.2"),
    Pkg.PackageSpec(name="WAV", version="1"),
])

using ZwickerLoudnessAudio: band_levels
using WAV: wavread
using Downloads
using Printf

const BASE = "https://raw.githubusercontent.com/Eomys/MoSQITo/master/validations/sq_metrics/sharpness_din/input"

# (center frequency [Hz], wav file, reference sharpness [acum])
const NARROWBAND = [
    (250,   "narrowband_250.WAV",   0.38),
    (350,   "narrowband_350.wav",   0.49),
    (450,   "narrowband_450.wav",   0.60),
    (570,   "narrowband_570.wav",   0.71),
    (700,   "narrowband_700.wav",   0.82),
    (840,   "narrowband_840.wav",   0.93),
    (1000,  "narrowband_1000.wav",  1.00),
    (1170,  "narrowband_1170.wav",  1.13),
    (1370,  "narrowband_1370.wav",  1.26),
    (1600,  "narrowband_1600.wav",  1.35),
    (1850,  "narrowband_1850.wav",  1.49),
    (2150,  "narrowband_2150.wav",  1.64),
    (2500,  "narrowband_2500.wav",  1.78),
    (2900,  "narrowband_2900.wav",  2.06),
    (3400,  "narrowband_3400.wav",  2.40),
    (4000,  "narrowband_4000.wav",  2.82),
    (4800,  "narrowband_4800.wav",  3.48),
    (5800,  "narrowband_5800.wav",  4.43),
    (7000,  "narrowband_7000.wav",  5.52),
    (8500,  "narrowband_8500.wav",  6.81),
    (10500, "narrowband_10500.wav", 8.55),
]

# (lower cutoff frequency [Hz], wav file, reference sharpness [acum])
const BROADBAND = [
    (250,  "broadband_250.wav",  2.70),
    (350,  "broadband_350.wav",  2.74),
    (450,  "broadband_450.wav",  2.78),
    (570,  "broadband_570.wav",  2.85),
    (700,  "broadband_700.wav",  2.91),
    (840,  "broadband_840.wav",  2.96),
    (1000, "broadband_1000.wav", 3.05),
    (1170, "broadband_1170.wav", 3.12),
    (1370, "broadband_1370.wav", 3.20),
    (1600, "broadband_1600.wav", 3.30),
    (1850, "broadband_1850.wav", 3.42),
    (2150, "broadband_2150.wav", 3.53),
    (2500, "broadband_2500.wav", 3.69),
    (2900, "broadband_2900.wav", 3.89),
    (3400, "broadband_3400.wav", 4.12),
    (4000, "broadband_4000.wav", 4.49),
    (4800, "broadband_4800.wav", 5.04),
    (5800, "broadband_5800.wav", 5.69),
    (7000, "broadband_7000.wav", 6.47),
    (8500, "broadband_8500.wav", 7.46),
]

function spl28(file, dir)
    path = joinpath(dir, file)
    Downloads.download("$BASE/$file", path)
    raw, fs, _, _ = wavread(path; format="native")
    eltype(raw) <: Int16 || error("$file: expected Int16 samples, got $(eltype(raw))")
    sig = Float64.(raw[:, 1]) ./ (2^15 - 1)
    spl = band_levels(sig, Float64(fs))
    overall = 10 * log10(sum(10 .^ (spl ./ 10)))
    @info file overall_dB = round(overall; digits=1)
    return spl
end

function emit(io, name, rows, dir)
    println(io, "const $name = [")
    for (fc, file, S) in rows
        vals = join((@sprintf("%.6f", v) for v in spl28(file, dir)), ", ")
        println(io, "    ($fc, $S, [$vals]),")
    end
    println(io, "]")
end

dir = mktempdir()
out = joinpath(@__DIR__, "..", "test", "data", "din45692_band_levels.jl")
mkpath(dirname(out))
open(out, "w") do io
    println(io, "# AUTOGENERATED by scripts/generate_din_reference.jl — do not edit by hand.")
    println(io, "# Each entry: (center/lower-cutoff frequency [Hz], reference sharpness")
    println(io, "# [acum], 28-band one-third-octave SPL [dB re 20 µPa]).")
    println(io, "# Derived from the DIN 45692:2009 ch.6 test signals vendored by MoSQITo")
    println(io, "# (Apache-2.0) — see test/data/NOTICE and test/data/LICENSE-MoSQITo.")
    emit(io, "DIN45692_NARROWBAND", NARROWBAND, dir)
    emit(io, "DIN45692_BROADBAND", BROADBAND, dir)
end
println("wrote $out")
