"""One-time generator for test/data/dw_fig3_references.jl.

Downloads MoSQITo's digitized Zwicker & Fastl roughness reference curves
(Apache-2.0, pinned commit) and evaluates ref_zf on the exact grid MoSQITo's
validation_roughness_danielweber.py gates on: fc x fmod, fm_vector
= [30..160]. Run:
    uv run --with numpy python scripts/generate_dw_fig3_references.py test/data/dw_fig3_references.jl
"""
import importlib.util
import os
import sys
import tempfile
import urllib.request

SHA = "d990c33f94f1"
URL = (f"https://raw.githubusercontent.com/Eomys/MoSQITo/{SHA}"
       "/validations/sq_metrics/roughness_dw/input/references.py")

# NOTE: urlretrieve()'s default temp filename has no extension, which makes
# spec_from_file_location() unable to infer a loader (returns None on any
# Python version). Fetch straight into a .py-suffixed temp file instead.
fd, path = tempfile.mkstemp(suffix=".py")
os.close(fd)
urllib.request.urlretrieve(URL, path)
spec = importlib.util.spec_from_file_location("references", path)
refs = importlib.util.module_from_spec(spec)
spec.loader.exec_module(refs)

FC = [125, 250, 500, 1000, 2000, 4000, 8000]
FM = [30, 40, 50, 60, 70, 80, 90, 100, 120, 140, 160]

lines = [
    "# AUTOGENERATED by scripts/generate_dw_fig3_references.py — do not edit.",
    f"# (fc [Hz], fmod [Hz], reference roughness [asper]) from MoSQITo commit {SHA},",
    "# validations/sq_metrics/roughness_dw/input/references.py —",
    "# ref_zf: digitized Zwicker & Fastl curves (the compliance gate);",
    "# ref_dw: digitized Daniel & Weber 1997 curves (informational only).",
    "# Apache-2.0, see test/data/NOTICE.",
]
for name, fn in (("DW_FIG3_REF_ZF", refs.ref_zf), ("DW_FIG3_REF_DW", refs.ref_dw)):
    lines.append(f"const {name} = [")
    for fc in FC:
        for fm in FM:
            lines.append(f"    ({fc}, {fm}, {float(fn(fc, fm))!r}),")
    lines.append("]")
open(sys.argv[1], "w").write("\n".join(lines) + "\n")
print(f"wrote {sys.argv[1]}: {len(FC) * len(FM)} points x 2 tables")
