# One-time generator for test/data/sqat_fs_crosscheck.jl.
#
# Synthesizes the cross-check signals with this package's own stimulus
# generator (test/support/fs_stimuli.jl), hands them to the pinned SQAT
# reference (github.com/ggrecow/SQAT @
# 00b449e40599f1c1ef4abe0596094552213d57eb, CC BY-NC) via Octave
# (scripts/run_sqat_fs.m), vendors the per-frame results as Julia
# fixtures.
#
# Requires: Octave with the octave-signal package installed, and the
# pinned checkout at /tmp/sqat-pinned (see .superpowers/sdd/fs-oracle-pins.md
# Step 1).
#
# Usage: julia --project=. scripts/generate_sqat_fs_crosscheck.jl
include(joinpath(@__DIR__, "..", "test", "support", "fs_stimuli.jl"))

const SQAT_DIR = get(ENV, "SQAT_DIR", "/tmp/sqat-pinned")
const CASES = [
    "anchor_44k", "anchor_48k", "am_8hz_70db", "fm_tone_4hz",
    "am_bbn_4hz", "stationary_anchor", "short_fallback", "tone_25bark",
]

isdir(SQAT_DIR) || error("pinned SQAT checkout not found at $SQAT_DIR — clone+checkout per Step 1 first")

workdir = mktempdir()
manifest_entries = String[]
for name in CASES
    sig, fs, method = synthesize_case(name)
    bin_path = joinpath(workdir, "$name.bin")
    open(bin_path, "w") do io
        write(io, sig)
    end
    push!(manifest_entries, """{"name": "$name", "fs": $fs, "method": $method, "signal_path": "$bin_path"}""")
end
manifest_path = joinpath(workdir, "manifest.json")
write(manifest_path, "[" * join(manifest_entries, ",") * "]")

output_dir = joinpath(workdir, "out")
driver = joinpath(@__DIR__, "run_sqat_fs.m")
run(`octave --no-gui $driver $manifest_path $output_dir $SQAT_DIR`)

octave_version = strip(read(`octave --eval "disp(OCTAVE_VERSION)"`, String))
signal_version = strip(read(`octave --eval "pkg load signal; disp(ver('signal').Version)"`, String))

jsonvec(v) = "[" * join(v, ", ") * "]"

function parse_json_number_array(text, key)
    # Minimal hand-rolled extraction: the driver's JSON is a flat object of
    # scalars/number arrays, so a simple bracket scan suffices without a
    # JSON dependency (matches this repo's existing generator scripts).
    m = match(Regex("\"$key\"\\s*:\\s*(\\[[^\\]]*\\]|[-0-9.eE]+)"), text)
    m === nothing && error("key $key not found")
    raw = m.captures[1]
    if startswith(raw, "[")
        return parse.(Float64, split(strip(raw, ['[', ']']), ","))
    else
        return parse(Float64, raw)
    end
end

lines = String[]
push!(lines, "# AUTOGENERATED by scripts/generate_sqat_fs_crosscheck.jl — do not edit.")
push!(lines, "# (name, fs, method, fluct [vacil, per analysis frame], t [s, per frame],")
push!(lines, "#  fs_mean [vacil], specific_tavg [vacil/Bark, 47 channels]) computed by")
push!(lines, "# SQAT's FluctuationStrength_Osses2016 (CC BY-NC, github.com/ggrecow/SQAT")
push!(lines, "# @ 00b449e40599f1c1ef4abe0596094552213d57eb) under Octave $octave_version")
push!(lines, "# (octave-signal $signal_version), on signals synthesized by this package's")
push!(lines, "# own test generator (test/support/fs_stimuli.jl) — any disagreement is a")
push!(lines, "# transcription bug, not a difference in stimulus.")
push!(lines, "const SQAT_FS_CASES = [")
for name in CASES
    text = read(joinpath(output_dir, "$name.json"), String)
    fs = parse_json_number_array(text, "fs")
    method = parse_json_number_array(text, "method")
    fluct = parse_json_number_array(text, "fluct")
    t = parse_json_number_array(text, "t")
    fs_mean = parse_json_number_array(text, "fs_mean")
    specific_tavg = parse_json_number_array(text, "specific_tavg")
    push!(lines, "    (name = \"$name\", fs = $fs, method = $(Int(method)), fluct = $(jsonvec(fluct)), t = $(jsonvec(t)), fs_mean = $fs_mean, specific_tavg = $(jsonvec(specific_tavg))),")
end
push!(lines, "]")

out_path = joinpath(@__DIR__, "..", "test", "data", "sqat_fs_crosscheck.jl")
write(out_path, join(lines, "\n") * "\n")
println("wrote $out_path: $(length(CASES)) cases")
for name in CASES
    text = read(joinpath(output_dir, "$name.json"), String)
    println("  $name: fs_mean = $(parse_json_number_array(text, "fs_mean"))")
end
